#!/bin/sh

[ -z "$LASTCONNECTIONERROR" ] && exit 0

INTERFACE=$6

. /usr/share/libubox/jshn.sh

json_init
json_add_string lastconnectionerror ""
ubus call "network.interface.$INTERFACE" set_data "$(json_dump)"
